server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  location = / {
    try_files /index.html =404;
  }

  location = /widget.js {
    default_type application/javascript;
    try_files /widget.js =404;
  }

  location = /widget/js {
    default_type application/javascript;
    try_files /widget.js =404;
  }

  location / {
    try_files $uri =404;
  }
}
